### ISSUE TITLE
通过id查询报错

### ISSUE THREAD

**Issue by MinJieLiu** [thinkgem/jeesite#140]
BaseService.getIdList 方法内将id判断为Long类型才可查询，应该为String类型。

**Comment by huguangju** [comment]
你是怎么写的？

**Comment by MinJieLiu** [comment]
protected List<String> getIdList(String ids) {
        List<String> idList = Lists.newArrayList();
        if (StringUtils.isNotBlank(ids)) {
            ids = ids.trim().replace("　", ",").replace(" ", ",").replace("，", ",");
            String[] arrId = ids.split(",");
            for (String id : arrId) {
                // if(id.matches("\\d*")) {
                idList.add(String.valueOf(id));
                // }
            }
        }
        return idList;
    }

**Comment by huguangju** [comment]
本系统只在下边这句用到了getIdList方法，共两处
```java
dc.add(Restrictions.in("id", getIdList(leave.getIds())));
```
leave.getIds()返回形如``` 1,2,3 ```的id列表，由getIdList()方法转成对应List。
Restrictions.in的形参为Restrictions.in(String propertyName, Collection values)，getIdList()返回```List<Long>```或```List<String>```都没问题，values最终都会转成Object[]

> 上边的```id.matches("\\d*")```应该加上，避免传入非法的值

想不出什么地方会引起错误

**Comment by MinJieLiu** [comment]
如 ids 分离出来的 id 为32位的uuid
就不能用
、、、java
idList.add(Long.valueOf(id));
、、、

**Comment by huguangju** [comment]
那是当然会出问题的。再写一个方法处理uuid的情况就行了。
