### ISSUE TITLE
pom.xml- poi.version-依赖问题

### ISSUE THREAD

**Issue by Notedown-cn** [thinkgem/jeesite#156]
pom.xml

```				    
                   <groupId>org.apache.poi</groupId>
			       <artifactId>poi</artifactId>
957行  	  -		<version>3.2-FINAL</version>  
              +        <version>${poi.version}</version>  
```

会导致项目依赖使用的是3.2-FINAL版本 编译utils-->excel 等包出错

antrun:run     数据库初始化的需使用3.2-FINAL 版本 

程序运行需要  <version>${poi.version}</version>   版本

**Comment by liyouhai** [comment]
antrun:run     数据库初始化的需使用3.2-FINAL 版本 

程序运行需要  <version>${poi.version}</version>   版本  
干脆就直接     pom.xml  957行
```
<groupId>org.apache.poi</groupId>
 <artifactId>poi</artifactId>
<!--  <version>3.2-FINAL</version>-->			
```
