### ISSUE TITLE
 工程jar包不能下载

### ISSUE THREAD

**Issue by Nick-yzm** [thinkgem/jeesite#188]
pom文件里面的很多包，都下载不下来，在家和公司都试过了，应该不是网络问题，你们怎么解决的。

**Comment by MarkHsiu** [comment]
我换了资源库 http://mvnrepository.com/artifact/

**Comment by Nick-yzm** [comment]
现在仓库用不了，我用了vpn 连接解决

**Comment by shenyun** [comment]
有些包不能下载是怎么解决的

**Comment by duxiaolong** [comment]
@shenyun 我当时缺少3个包，下不下来，我最后手动导入了。
