### ISSUE TITLE
项目依赖无法解决

### ISSUE THREAD

**Issue by xingguang2013** [thinkgem/jeesite#193]
pom文件中关于几个依赖：
        <dependency>
            <groupId>bitwalker</groupId>
            <artifactId>UserAgentUtils</artifactId>
            <version>1.13</version>
        </dependency>
        <dependency>
            <groupId>com.ckfinder</groupId>
            <artifactId>apache-ant-zip</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>com.ckfinder</groupId>
            <artifactId>ckfinder</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>com.ckfinder</groupId>
            <artifactId>ckfinderplugin-fileeditor</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>com.ckfinder</groupId>
            <artifactId>ckfinderplugin-imageresize</artifactId>
            <version>2.3</version>
        </dependency>
上面几个依赖关系无法解决，请帮忙看下在哪个仓库有这些jar，谢谢

**Comment by simpledong81** [comment]
作者自己的github仓库里面有
我下载下来放到自己的仓库了

**Comment by xingguang2013** [comment]
非常感谢，找到了
