### ISSUE TITLE
在使用系统自带功能“在线办公-通告管理”的添加功能时，出现的添加失败的问题

### ISSUE THREAD

**Issue by tolower** [thinkgem/jeesite#202]
主要异常信息：
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'dbName' not found. Available parameters are [list]

发现是在OaNotifyRecordDao.xml中insertAll的问题：
（提示dbName找不着……）

\<insert id="insertAll" parameterType="List"\>
		INSERT INTO OA_NOTIFY_RECORD(
			ID,
			OA_NOTIFY_ID,
			USER_ID,
			READ_FLAG,
			READ_DATE
		)
		\<foreach collection="list" item="e" separator=" UNION ALL "\>
			SELECT
				#{e.id},
				#{e.oaNotify.id},
				#{e.user.id},
				#{e.readFlag},
				#{e.readDate}
			_\<if test="dbName != 'mssql'"\>_
			FROM dual
			\</if\>
		\</foreach\>
	\</insert\>

**Comment by tolower** [comment]
最后修改了\<if test="dbName != 'mssql'"\>这个语句中的*dbName*为*e.dbName* ，貌似解决了问题。

我的系统环境为win7+jdk7+tomcat7，不知道有没有人遇到这个问题？

**Comment by whiliang** [comment]
一样遇到了这个问题, Env：win7+jdk7+tomcat7

**Comment by tolower** [comment]
那你修改后是否正常了？

**Comment by whiliang** [comment]
按你的修改后正常了。
