### ISSUE TITLE
角色修改页面的归属机构的值有问题

### ISSUE THREAD

**Issue by lihao20050525** [thinkgem/jeesite#206]
系统设置->角色管理->角色修改中的归属机构的显示值与之前选中的值不符，列表页面是正确的。

**Comment by jgroups** [comment]
你看这个
https://github.com/thinkgem/jeesite/pull/334
,我已经修复了.
主要就是英文从数据库拿角色时,归属机构没有选出来,导致了归属机构为当前登录用户的归属部门信息.
