### ISSUE TITLE
Intellij-Idea 下安装 jeesite1.2.6，及mac下安装（分享、记录）

### ISSUE THREAD

**Issue by zhengvince** [thinkgem/jeesite#229]
1. 修改jeesite.properties里的数据库用户名密码。
2. 修改pom.xml内的pio版本，查找“3.2-FINAL”替换为“${poi.version}”。
3. 运行bin\init-db.bat脚本，即可导入表结构及演示数据(mac操作系统：在控制台中切换至项目根目录，运行命令：mvn antrun:run -Pinit-db)

4.打开idea，import导入pom.xml

5.Idea中配置project structure,添加spring依赖（或者在src/main/resources内打开一个spring...xml,根据ide上面提示添加依赖）

**Comment by imageslr** [comment]
没有问题。第五步“Idea中配置project structure,添加spring依赖（或者在src/main/resources内打开一个spring...xml,根据ide上面提示添加依赖）”我没有使用，直接就有了，可能是我之前安装过了吧。
