### ISSUE TITLE
导入数据表并初始化数据错误

### ISSUE THREAD

**Issue by 939347507** [thinkgem/jeesite#230]
执行mvn antrun:run -Pinit-db命令出现如下错误：

[INFO] Executing tasks

main:
      [sql] Executing resource: D:\code\working\jeesite\db\sys\jeesite_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\cms\jeesite_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\oa\jeesite_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\gen\jeesite_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\gen\example_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\test\jeesite_mysql.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\drop\activiti.mysql.drop.engine.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\drop\activiti.mysql.drop.history.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\drop\activiti.mysql.drop.identity.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\create\activiti.mysql.create.engine.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\create\activiti.mysql.create.history.sql
      [sql] Executing resource: D:\code\working\jeesite\db\act\create\activiti.mysql.create.identity.sql
      [sql] 296 of 296 SQL statements executed successfully
   [dbunit] Executing operation: INSERT
   [dbunit]           on   file: D:\code\working\jeesite\db\sys\jeesite_data.xls
   [dbunit]           with format: xls
[ERROR] execute: table.column=sys_menu.href value is empty but must contain a value
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:26 min
[INFO] Finished at: 2016-01-10T14:34:57+08:00
[INFO] Final Memory: 17M/93M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default-cli) on project jeesite: An Ant BuildException has occured: java.lang.IllegalArgumentException: table.column=sys_menu.href value is empty but must contain a value
[ERROR] around Ant part ...<dbunit password="${jdbc.password}" driver="${jdbc.driver}" userid="${jdbc.username}" url="${jdbc.url}">... @ 22:107 in D:\code\working\jeesite\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Joezc** [comment]
请问你是怎么解决这个问题的？
