### ISSUE TITLE
用户权限错误

### ISSUE THREAD

**Issue by zhoujiangzi** [thinkgem/jeesite#238]
测试步骤：
1. 新增一个角色，该角色有创建用户的权限，但是是一个普通的角色，拥有少量的菜单
2.在该角色下面新增一个用户
3.使用该用户登陆系统，新增一个用户，在勾选角色时，可以将超级管理员的角色一并勾选
4.再次使用最后新增的用户进行系统登陆，此时会发现该用户拥有超级管理员的角色。

希望在新增用户时，列出来的角色不是所有的角色，而是根据当前用户的角色来进行显示

**Comment by jinjingmail** [comment]
这个问题貌似很严重。

**Comment by think-gem** [comment]
这里的角色和权限有关，读取的分配角色查询调用方法为UserUtils.getRoleList()，角色中有归属部门和数据范围就是控制这个的。
