### ISSUE TITLE
maven多个依赖包下载不到，你们是怎么运行起来的呀

### ISSUE THREAD

**Issue by kiwiflydream** [thinkgem/jeesite#243]
搞了2个小时，还没把包集齐，maven仓库里面根本没有，很好奇各位大神是怎么运行起来的，
只找到其中几个http://download.csdn.net/download/u010137431/9268707

**Comment by gxz1989611** [comment]
在pom.xml里添加一个这个呢
`<repository>
	<id>oschina-thirdparty</id>
	<name>Oschina thirdparty</name>
	<url>http://maven.oschina.net/content/repositories/thirdparty/</url>
</repository>
`

**Comment by think-gem** [comment]
缺少的文件已传到lib目录下，临时解决这个问题。

**Comment by kiwiflydream** [comment]
谢谢
