### ISSUE TITLE
文件编码能否统一为UTF-8？中文都乱码

### ISSUE THREAD

**Issue by ryomasaber** [thinkgem/jeesite#244]
批处理都是.bat 能增加.sh就好了啊 喵~~

**Comment by baiyueguang** [comment]
第一份文档的安装部分倒数第二条，请修改tomcat编码。uriencodin=utf-8

**Comment by ryomasaber** [comment]
和tomcat编码没关系 是项目文件编码  我都是UTF8 你的是GBK 所以中文乱码

**Comment by baiyueguang** [comment]
懂你的意思了，文件打开有乱码。配置文件你可以下个工具propertiesEditor   ，java里没发现汉字乱码

**Comment by ryomasaber** [comment]
嘿嘿 是bin下面的8个批处理文件乱码 默认编码为GBK 这个不算太大的问题 谢谢你的回复哈O(∩_∩)O！
