### ISSUE TITLE
自动生成代码时数据库字段名称特殊，则生成实体类不符合java bean标准。

### ISSUE THREAD

**Issue by Csdypg** [thinkgem/jeesite#247]
例如字段名成为a_abc_def，则生成属性为aAbcDef,
getter方法为 getAAbcDef(),不符合java bean规范,
应该为getaAbcDef()，
否则导致jsp文件中ｅｌ表达式无法获取属性。

**Comment by think-gem** [comment]
是有这个问题，建议命名时避免这种命名方式。
