### ISSUE TITLE
区域添加的bug

### ISSUE THREAD

**Issue by dongqisilent** [thinkgem/jeesite#256]
系统设置--》区域管理--》区域添加 点击时候直接报空指针异常。
com.thinkgem.jeesite.modules.sys.web.AreaController 64行代码

   area.setParent(areaService.get(area.getParent().getId()));
修改为
   if(area.getParent()!=null){
			area.setParent(areaService.get(area.getParent().getId()));
		}
能解决问题，但是不知道这种方案会不会有其他的问题？

**Comment by think-gem** [comment]
上边有一个area.getParent()空值判断，可能是你的必填的UserUtils.getUser().getOffice().getArea()为空。
