### ISSUE TITLE
为什么请求这么一个地址

### ISSUE THREAD

**Issue by wallellen** [thinkgem/jeesite#258]
你好， 在 SpringContextHolder.java 中为什么会请求一个很奇怪的地址？http://hm.baidu.com/hm.gif?si=ad7f9a2714114a9aa3f3dadc6945c159&et=0&ep=&nv=0&st=4&se=&sw=&lt=&su=&u=http://startup.jeesite.com/version/V1.1.0&v=wap-2-0.3&rnd=时间   而且貌似故意不想让人知道在请求这个地址

**Comment by summer00** [comment]
这个应该是百度统计的一个链接，可能是广告中的收集用户信息的看不见的一个1*1的像素

think-gem committed Mar 19, 2015 2a82b1b2d2c15ef7189d4dd95679e56007a3f2c0

还请作者说明这段代码的用途，谢谢

**Comment by shenyun** [comment]
请问一下，你们是怎么运行起来的，我拿到maven的版本，有些jar更本没法下载，作者也没有提供不能下载的jar,难道都是自己去找寻的？

**Comment by wallellen** [comment]
@summer00  应该是， JSP里大概有几十个类似的地址

**Comment by wallellen** [comment]
@shenyun ， 我使用的是hibernate的分支， 没有使用主干， 我不太喜欢用mybatis， 纯属个人爱好，无关技术好坏

**Comment by heimasi** [comment]
这个就是baidu统计，注意里写的很明白。不需要的话可以去掉，需要的话可以换成自己的key和欣喜

**Comment by wallellen** [comment]
@heimasi , 谢谢

**Comment by think-gem** [comment]
百度统计，起初是想统计版本使用情况的，可删除！

**Comment by wallellen** [comment]
@think-gem  谢谢
