### ISSUE TITLE
强烈要求作者将更新后的后续功能放出来，放到github上来，不然你开这个有何意义？

### ISSUE THREAD

**Issue by wangyang12611** [thinkgem/jeesite#300]
强烈要求作者将更新后的后续功能放出来，放到github上来，不然你开这个有何意义？比如QQ群里面的他人增加的全文检索，cxf集成等完善功能，QQ群又不加人，这里又不新增代码真着急

**Comment by think-gem** [comment]
qq群可以加人，你加不进去吗
