### ISSUE TITLE
db/init-db.bat 乱码

### ISSUE THREAD

**Issue by jeffhtli** [thinkgem/jeesite#305]
db/init-db.bat 乱码

**Comment by liuyan52** [comment]
怎么解决的？

**Comment by jeffhtli** [comment]
已经好了吧

**Comment by liuyan52** [comment]
没有，就tomcat log里面还有



---原始邮件---
发件人: "Li Haitao"<notifications@github.com&gt;
发送时间: 2020年12月30日(周三) 下午3:24
收件人: "thinkgem/jeesite"<jeesite@noreply.github.com&gt;;
抄送: "liuyan52"<2356131067@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [thinkgem/jeesite] db/init-db.bat 乱码 (#305)




 
已经好了吧
