### ISSUE TITLE
我喜欢nutz框架 可以来个nutz框架版本么

### ISSUE THREAD

**Issue by HaimmingYu** [thinkgem/jeesite#350]
我喜欢nutz框架 可以来个nutz框架版本么

**Comment by wentan4617** [comment]
喜欢就自己改一下呗。又能学习又能锻炼。程序员要自己动手写东西吗。哈哈

**Comment by hzl7652** [comment]
集成nutz就可以了，我们现在是dao和工具类用nutz， mvc ioc 还是spring

**Comment by TonyYule** [comment]
nutz一个就够了 spring都不用
