### ISSUE TITLE
有没有提供非maven版本的？

### ISSUE THREAD

**Issue by pinegit123** [thinkgem/jeesite#378]
项目是用maven管理的，是不错！但有没有提过非maven版本的？毕竟有些公司不使用maven哦

**Comment by SuperGod110** [comment]
同感  但是直接使用也还行

**Comment by think-gem** [comment]
很简单哦，你新建一个普通工程吧src拷贝过去，通过maven package导出war包，然后把里面的lib也拷贝过去，就ok了。
