### ISSUE TITLE
不允许重复用户登录存在bug

### ISSUE THREAD

**Issue by izhoujie** [thinkgem/jeesite#384]
当前不允许重复用户登录开启设置后，代码的实际处理是踢掉了所有当前在线用户：
`jeesite/src/main/java/com/thinkgem/jeesite/modules/sys/security/SystemAuthorizingRealm.java
                         if (sessions.size() > 0){
				// 如果是登录进来的，则踢出已在线用户
				if (UserUtils.getSubject().isAuthenticated()){
					for (Session session : sessions){
						getSystemService().getSessionDao().delete(session);
					}
				} `
应该改成:
`			if (sessions.size() > 0){
				// 如果是登录进来的，则踢出已在线用户
				if (UserUtils.getSubject().isAuthenticated()){
					for (Session session : sessions){			
						String tmpId = String.valueOf(session.getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY));
					     //清除该用户以前登录时保存的session
						if(id.equals(tmpId))
						   getSystemService().getSessionDao().delete(session);
					}
				}
`
不允许单个用户重复登录 而不是不允许同一时间只能有一个用户在线。

**Comment by duyishuaixue** [comment]
棒，你可以申请提交代码的权限，共同完善这个系统。
对了，你有使用jeesite 负载均衡实现session共享吗？

**Comment by javyuan** [comment]
此处并无bug，你看下com.thinkgem.jeesite.common.security.shiro.session.CacheSessionDAO的getActiveSeesions方法就知道了
![image](https://cloud.githubusercontent.com/assets/2009474/23687909/0d5b97c2-03ec-11e7-8017-e3e1b8f1ebbf.png)

**Comment by izhoujie** [comment]
代码可能看着没差；
但是不是真有bug，还是自己跑起来看看吧。

**Comment by Wunmest** [comment]
`if (principal != null) {
} 
else {
// 把 includeLeave 放到这里吧
}`

**Comment by Wunmest** [comment]
重复用户登录和记住我这两个功能是不是不能同时满足？

**Comment by javyuan** [comment]
![image](https://user-images.githubusercontent.com/2009474/27817946-2bce00f0-60c6-11e7-9d54-7fe8fbeee1c2.png)
在CacheSessionDAO.java加个else，解决。

**Comment by smallyaohailu** [comment]
感谢，我抽时间研究下。
