### ISSUE TITLE
jquery append 无法渲染到页面

### ISSUE THREAD

**Issue by pinegit123** [thinkgem/jeesite#396]
想使用jquery 中的append方法把数据动态渲染到select标签里，却渲染不成。返回有数据就是页面加载不了。求解！

**Comment by javyuan** [comment]
页面中的select会先被渲染成select2，通过浏览页面源代码找到被渲染后的dom再append试试。

**Comment by pinegit123** [comment]
好的，不过已解决，append的内容转换成jquery对象即可。
