### ISSUE TITLE
excel导出中文名乱码

### ISSUE THREAD

**Issue by authasme** [thinkgem/jeesite#402]
数据导出功能，在firfox下文件名中文乱码，在chrome下正常

**Comment by ppx-build-code** [comment]
火狐下存在这种问题，你可以找找网上的教程，修改write方法，判断下是火狐的话单独处理

**Comment by ttlcom** [comment]
filename.getBytes("gbk"), "iso8859-1"

**Comment by hzl7652** [comment]
使用SpringSide 的 Servlets.setFileDownloadHeader方法设置
[https://github.com/springside/springside4/blob/9f6989924f325de05b1f2cfa19ee261c752d211c/modules/core/src/main/java/org/springside/modules/web/Servlets.java](SpringSide Servlets)
