### ISSUE TITLE
当点击某个菜单链接时,出现页面不存在,该如何调试?

### ISSUE THREAD

**Issue by sheldonshen** [thinkgem/jeesite#407]
如题,此时系统及没有异常日志,也没有错误,该如何调试,才能找到原因所在.

**Comment by meaningful** [comment]
(⊙o⊙)… 围观

**Comment by d87335903** [comment]
@meaningful ,别关围观哈,帮忙找下办法啥.:smile:

**Comment by irongroup** [comment]
链接找对应的controller 
找到了controller 再找对应的返回页面
一般都能找到原因的

**Comment by BruceBeyond** [comment]
还可能是你设置页面路径弄错了

**Comment by zjfchinese** [comment]
菜单配完权限和路径后要重启下项目服务器
