### ISSUE TITLE
代码生成生成包路径问题

### ISSUE THREAD

**Issue by pinegit123** [thinkgem/jeesite#408]
代码生成中生成包路径不使用建议模块包（com.thinkgem.jeesite.modules）命名，使用自定义包命名后无法打开页面。

**Comment by ppx-build-code** [comment]
你可以看看你控制层指向的路径以及对应的j s p文件的路径是不是对应上了

**Comment by xiyang10826670** [comment]
在jeesite.properties下的projectPath修改
