### ISSUE TITLE
jeesite平台是如何处理系统中的异常的?

### ISSUE THREAD

**Issue by sheldonshen** [thinkgem/jeesite#409]
如题,研究了半天,也没有看出来,jeesite是如何对系统的异常是如何做出统一处理的.希望知道的,能指点一下.

**Comment by irongroup** [comment]
看spring-mvc.xml 里面的这段
<bean class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver">
		<property name="exceptionMappings">
			<props>
				<prop key="org.apache.shiro.authz.UnauthorizedException">error/403</prop>
				<prop key="java.lang.Throwable">error/500</prop>
			</props>
			</property>
	</bean>

**Comment by javyuan** [comment]
那可以把BaseController里的
	
	/**
	 * 参数绑定异常
	 */
	@ExceptionHandler({BindException.class, ConstraintViolationException.class, ValidationException.class})
    public String bindException() {  
        return "error/400";
    }
	
	/**
	 * 授权登录异常
	 */
	@ExceptionHandler({AuthenticationException.class})
    public String authenticationException() {  
        return "error/403";
    }

也写到spring-mvc.xml里了，方便统一管理。

**Comment by sheldonshen** [comment]
@irongroup , @javyuan ,多谢.:smile:
