### ISSUE TITLE
jeesite怎么变英文版,怎么快速应用于国外市场??

### ISSUE THREAD

**Issue by ithjz** [thinkgem/jeesite#448]
jeesite怎么变英文版,怎么快速应用于国外市场??

**Comment by think-gem** [comment]
您好，

spring国际化

                       致
礼！
                             2017-12-21 


ThinkGem
 
发件人： ithjz
发送时间： 2017-12-21 11:55
收件人： thinkgem/jeesite
抄送： Subscribed
主题： [thinkgem/jeesite] jeesite怎么变英文版,怎么快速应用于国外市场?? (#448)
 
jeesite怎么变英文版,怎么快速应用于国外市场??

**Comment by wentan4617** [comment]
我去，程序不是变出来的。这个问题真不像是程序员问的。

**Comment by ithjz** [comment]
谢谢,正是我想要答案,好的,我好好研究下 spring国际化的

**Comment by smallyaohailu** [comment]
Report content: https://github.com/thinkgem/jeesite/issues/448

您说的在编程领域内名为国际化

您可以写一个代码生成器，写一个中文版本的property。
然后把中文版本自动翻译成100多个国家的语言，然后再配置到各个国家的property文件内。。。。就是适应各种国家的语言了。
但是肯定不准确，还是要人工矫正。
