### ISSUE TITLE
基于jeesite的平台里,我自己写了个简单的 文件上传,方法, 但是每次拿List<FileItem> /* FileItem */items = upload.parseRequest(request);都是null

### ISSUE THREAD

**Issue by ithjz** [thinkgem/jeesite#449]
基于jeesite的平台里,我自己写了个简单的 文件上传,方法, 但是每次拿List<FileItem> /* FileItem */items = upload.parseRequest(request);都是null

应该怎么改

// Create a factory for disk-based file items
			DiskFileItemFactory factory = new DiskFileItemFactory();
			
//			FileCleaningTracker fileCleaningTracker = 
//					FileCleanerCleanup.getFileCleaningTracker(getServletContext());
//			factory.setFileCleaningTracker(fileCleaningTracker);
			
			// Set factory constraints
			factory.setSizeThreshold(1024 * 500);
			File tempDirectory = new File("d:\\tempDirectory");
			factory.setRepository(tempDirectory);

			// Create a new file upload handler
			ServletFileUpload upload = new ServletFileUpload(factory);

			// Set overall request size constraint
			upload.setSizeMax(1024 * 1024 * 5);

			// Parse the request
			try {
				List<FileItem> /* FileItem */items = upload.parseRequest(request);
				
				
				System.out.println("--items---" +items);

`/**
 * Copyright &copy; 2012-2014 <a href="https://github.com/thinkgem/jeesite">JeeSite</a> All rights reserved.
 */
package com.thinkgem.jeesite.modules.sys.web;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.URLEncoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.fileupload.FileItem;
import org.apache.commons.fileupload.FileUploadException;
import org.apache.commons.fileupload.disk.DiskFileItemFactory;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.thinkgem.jeesite.common.config.Global;
import com.thinkgem.jeesite.common.utils.StringUtils;
import com.thinkgem.jeesite.common.utils.UploadUtils;
import com.thinkgem.jeesite.common.web.BaseController;

/**
 * 下载Controller
 * @author 
 * @version 2017-12-23
 */
@Controller
@RequestMapping(value = "${adminPath}/down")
public class DownLoadController extends BaseController {
	
	//http://localhost:8080/glassTry/a/down/upload
		@RequestMapping(value="upload")
		public void  upload(HttpServletRequest request, HttpServletResponse response) throws Exception {
			
			System.out.println("--upload----upload---");
			// 1. 得到 FileItem 的集合 items
			// Create a factory for disk-based file items
			DiskFileItemFactory factory = new DiskFileItemFactory();
			
//			FileCleaningTracker fileCleaningTracker = 
//					FileCleanerCleanup.getFileCleaningTracker(getServletContext());
//			factory.setFileCleaningTracker(fileCleaningTracker);
			
			// Set factory constraints
			factory.setSizeThreshold(1024 * 500);
			File tempDirectory = new File("d:\\tempDirectory");
			factory.setRepository(tempDirectory);

			// Create a new file upload handler
			ServletFileUpload upload = new ServletFileUpload(factory);

			// Set overall request size constraint
			upload.setSizeMax(1024 * 1024 * 5);

			// Parse the request
			try {
				List<FileItem> /* FileItem */items = upload.parseRequest(request);
				
				
				System.out.println("--items---" +items);

				// 2. 遍历 items:
				for (FileItem item : items) {
					// 若是一个一般的表单域, 打印信息
					if (item.isFormField()) {
						String name = item.getFieldName();
						String value = item.getString();
						System.out.println(name + ": " + value);
						
					}
					// 若是文件域则把文件保存到 d:\\files 目录下.
					else {
						String fieldName = item.getFieldName();
						String fileName = item.getName();
						String contentType = item.getContentType();
						long sizeInBytes = item.getSize();

						System.out.println(fieldName);
						System.out.println(fileName);
						System.out.println(contentType);
						System.out.println(sizeInBytes);

						InputStream in = item.getInputStream();
						byte[] buffer = new byte[1024];
						int len = 0;
						
						if (null!=fileName&&!"".equals(fileName)) {
							
							System.out.println("--文件存在--"+ fieldName);
							
						}else {
							System.out.println(fileName+"--找不到--");
						     break;
						}
						
						
						fileName = "d:\\files\\" + fileName;
						System.out.println(fileName);

						OutputStream out = new FileOutputStream(fileName);

						while ((len = in.read(buffer)) != -1) {
							out.write(buffer, 0, len);
						}

						out.close();
						in.close();
					}
				}

			} catch (FileUploadException e) {
				e.printStackTrace();
			}
		}

			
		
	
	
	//http://localhost:8080/glassTry/a/down/image
	@RequestMapping(value="image")
	public void imageUpload(HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		System.out.println("---hjz file upload--");
//		ServletContext servletContext = request.getServletContext();
//		String savepath= servletContext.getRealPath(“/WEB-INF/uploads”);
		  // 因为要使用response打印，所以设置其编码
	       response.setContentType("text/html;charset=utf-8");
	      
	       // 创建工厂
	       DiskFileItemFactory dfif = new DiskFileItemFactory();
	       // 使用工厂创建解析器对象
	       ServletFileUpload fileUpload = new ServletFileUpload(dfif);
	       try {
	           // 使用解析器对象解析request，得到FileItem列表
	    	   UploadUtils   utils=new UploadUtils();
	    	   
	           List<FileItem> list = fileUpload.parseRequest(request);
	           
	           InputStream in = request.getInputStream();
	           InputStreamReader isr = new InputStreamReader(in);
	           BufferedReader bufr = new BufferedReader(isr);

	           String line = null;

	          

	           String[]  listhjz =utils.uploadFile(request);
	           System.out.println("---listhjz---" +listhjz.length);
	           
	           for (int i = 0; i < listhjz.length; i++) {
				    System.out.println("--listhjz---" +listhjz[i]);
			    }
	           
	           System.out.println("--list--" +list);
	           // 遍历所有表单项
	           for(FileItem fileItem : list) {
	              // 如果当前表单项为普通表单项
	              if(fileItem.isFormField()) {
	                  // 获取当前表单项的字段名称
	                  String fieldName = fileItem.getFieldName();
	                  // 如果当前表单项的字段名为username
	                  if(fieldName.equals("username")) {
	                     // 打印当前表单项的内容，即用户在username表单项中输入的内容
	                     response.getWriter().print("用户名：" + fileItem.getString() + "<br/>");
	                  }
	              } else {//如果当前表单项不是普通表单项，说明就是文件字段
	                  String name = fileItem.getName();//获取上传文件的名称
	                  // 如果上传的文件名称为空，即没有指定上传文件
	                  if(name == null || name.isEmpty()) {
	                     continue;
	                  }
	                  // 获取真实路径，对应${项目目录}/uploads，当然，这个目录必须存在
//	                  String savepath = this.getServletContext().getRealPath("/uploads");
	                  String savepath = "E:/";
	                  // 通过uploads目录和文件名称来创建File对象
	                  File file = new File(savepath, name);
	                  // 把上传文件保存到指定位置
	                  fileItem.write(file);
	                  // 打印上传文件的名称
	                  response.getWriter().print("上传文件名：" + name + "<br/>");
	                  // 打印上传文件的大小
	                  response.getWriter().print("上传文件大小：" + fileItem.getSize() + "<br/>");
	                  // 打印上传文件的类型
	                  response.getWriter().print("上传文件类型：" + fileItem.getContentType() + "<br/>");
	      			 System.out.println("---hjz -close--");

	              }
	           }
	       } catch (Exception e) {
	           throw new Exception(e);
	       }
	}
	
	
	
	
	
//	http://localhost:8080/product_admin/a/down/downloadApi
	
	@RequestMapping(value="downloadApi")
	public void download(HttpServletRequest request, 
			HttpServletResponse response) {
		
		System.out.println("--downloadApi--");
		String fileName="e://12202017glassForApi.doc";
		String downloadPath = request.getSession().getServletContext().getRealPath(Global.getConfig("downloadPath"));
		downloadPath = String.format("%s%s%s", downloadPath, "\\", fileName);
		downloadPath = downloadPath.replace('\\', File.separatorChar);
		
		try {
			File file = new File(fileName);
			if (!file.exists()) {
				System.out.println("找不到下载文件，URL地址为：%s。");
				logger.error(String.format("找不到下载文件，URL地址为：%s。", downloadPath));
				return;
			}
			
//			fileName = downloadPath.substring(downloadPath.lastIndexOf(File.separatorChar) + 1);
			response.reset();
			System.out.println("---fileName---" +fileName);
			
			response.setHeader("content-disposition", 
					"attachment;filename="  + "glassForApi.doc");

			response.setHeader("Content-Type", "application/zip");
			response.setContentType("application/force-download");
			
			FileInputStream inputStream = new FileInputStream(fileName);
			OutputStream outputStream = response.getOutputStream();
			byte[] buffer = new byte[1024];
			int len = 0;
			while ((len = inputStream.read(buffer)) > 0) {
				outputStream.write(buffer, 0, len);
			}
			inputStream.close();
			outputStream.close();
			System.out.println("---hjz -close--");
		} catch(Exception exception) {
			logger.error(String.format("下载文件失败，URL地址为：%s。", downloadPath), exception);
		}
	}
	
	
	
	
	/** 
	   * 文件下载 
	   * @param response 
	   * @param is 文件输入流 
	   * @param fileName 下载的文件名称 
	   * @param encoding 编码格式 
	   */ 
	  public static void download(HttpServletResponse response, InputStream is, String fileName, String encoding){ 
	    if(is == null || StringUtils.isBlank(fileName)){ 
	      return; 
	    } 
	     
	    BufferedInputStream bis = null; 
	    OutputStream os = null; 
	    BufferedOutputStream bos = null; 
	     
	    try{ 
	      bis = new BufferedInputStream(is); 
	      os = response.getOutputStream(); 
	      bos = new BufferedOutputStream(os); 
	      response.setContentType("application/octet-stream;charset=" + encoding); 
	      response.setCharacterEncoding(encoding); 
	      response.setHeader("Content-disposition", "attachment;filename="+ URLEncoder.encode(fileName, encoding)); 
	      byte[] buffer = new byte[1024]; 
	      int len = bis.read(buffer); 
	      while(len != -1){ 
	        bos.write(buffer, 0, len); 
	        len = bis.read(buffer); 
	      } 
	       
	      bos.flush(); 
	    }catch(IOException e){ 
	      e.printStackTrace(); 
	    }finally{ 
	      if(bis != null){ 
	        try{ 
	          bis.close(); 
	        }catch(IOException e){} 
	      } 
	       
	      if(is != null){ 
	        try{ 
	          is.close(); 
	        }catch(IOException e){} 
	      } 
	    } 
	  } 
}
`

**Comment by smallyaohailu** [comment]
有关文件上传下载相关您可以参考jeesite论坛上面的案例。
http://www.jeesite.net/forum.php?mod=viewthread&tid=286&highlight=upload
