### ISSUE TITLE
1.0.0版本的连接池0.7.1-rc2已失效

### ISSUE THREAD

**Issue by TracyJian** [thinkgem/jeesite#451]
1.0.0版本 boncp的0.7.1-rc2版本在maven中央库以及另外指定的BoneCP Repository中均无法下载，可以修改为 0.7.1-rc3 或更新的版本

**Comment by smallyaohailu** [comment]
最新版本的，已经更新为阿里的maven库，您可以使用最新版本。。。。老版本，遇到这类问题，您可以清理下.m2下的包。然后用 vpn翻墙后下载。

**Comment by TracyJian** [comment]
@smallyaohailu 感谢。最新版的没问题。
