### ISSUE TITLE
有没有spring boot 版本

### ISSUE THREAD

**Issue by wfm0105** [thinkgem/jeesite#452]
看了下，现在流行spring boot ，项目有没有spring boot 版本

**Comment by lcw2004** [comment]
@wfm0105 我之前基于spring boot 改了一个版本，现在改的除了数据库其他地方都不一样了，如果有兴趣可以看一下https://github.com/lcw2004/one

**Comment by smallyaohailu** [comment]
目前 基于jeesite修改的spring boot版本，官方并没有集成，  在github上，有其他开发者集成的spring boot版本。
官方jeesite 4.0是基于spring boot版本做的开发，预计明年jeesite 4.0可以正式上线。
