### ISSUE TITLE
MyBatis的相关代码是怎么生成的吗？

### ISSUE THREAD

**Issue by kuiblog** [thinkgem/jeesite#453]
第一个次用`jeesite`，想问一下大家，我看到`resource`中有很多MyBatis DAO相关的Mapping XML文件，这些文件是一个个手写的吗？还是通过工具可以生成呢？谢谢大家。

**Comment by think-gem** [comment]
大部分是生成的，个性化的小部分是手写。

**Comment by smallyaohailu** [comment]
jeesite的代码生成器，是内置的，基于mybatis官方自带的代码生成器，二次开发。
目前有关的教程 有长春叭哥的，可以快速入手
http://my.tv.sohu.com/pl/9428116/index.shtml
有大胖老师的，比较系统讲解。

如果想更快捷高效开发jeesite。可以购买jeesite2.0，页面比较漂亮，代码生成器也更为好用。
http://www.jeesite.net:8080/jeesite/a/
thinkgem admin
购买方式：联系我和thinkgem qq:78112665都可以，长春叭哥：3311247533@qq.com。

**Comment by kuiblog** [comment]
@smallyaohailu 非常感谢你，我先看一下。谢谢了。
