### ISSUE TITLE
上传的图片文件，重启服务器就没了

### ISSUE THREAD

**Issue by LyyDandelion** [thinkgem/jeesite#489]
上传的图片文件，重启服务器就没了，怎么处理呢？

**Comment by smallyaohailu** [comment]
userfile  的存储映射到 其他盘符  不用默认的

**Comment by LyyDandelion** [comment]
十分感谢！！



------------------ 原始邮件 ------------------
发件人: "姚海陆"<notifications@github.com>; 
发送时间: 2019年5月7日(星期二) 上午10:46
收件人: "thinkgem/jeesite"<jeesite@noreply.github.com>; 
抄送: "King&#x1F451;"<1354831622@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [thinkgem/jeesite] 上传的图片文件，重启服务器就没了 (#489)




userfile  的存储映射到 其他盘符  不用默认的
