### ISSUE TITLE
新增数据集权限控制

### ISSUE THREAD

**Issue by think-gem** [thinkgem/jeesite#55]
数据范围（1：所有数据；2：所在公司及以下数据；3：所在公司数据；4：所在部门及以下数据；5：所在部门数据；8：仅本人数据；9：按明细设置）
BaseService.dataScopeFilter(User user, String officeAlias, String userAlias);

**Comment by smallyaohailu** [comment]
JeeSite4.x 数据权限完整视频教程
https://ke.qq.com/course/408983?tuin=c55da0ad
